// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYjcPq19raPyTkJt2JkT1EO2PKhCmy2Lo',
    appId: '1:863696538947:web:d64a55da8edc4c1de733f6',
    messagingSenderId: '863696538947',
    projectId: 'couple-finance-pig',
    authDomain: 'couple-finance-pig.firebaseapp.com',
    storageBucket: 'couple-finance-pig.firebasestorage.app',
    measurementId: 'G-S2134DM151',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAP9qQ0hp0dFE-8LzduG4_xdFplt8e_oUM',
    appId: '1:863696538947:android:978fe46a1181fd67e733f6',
    messagingSenderId: '863696538947',
    projectId: 'couple-finance-pig',
    storageBucket: 'couple-finance-pig.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBp6IBfjoBQzvhAEXAH0qsZs8qBUwoy8Rc',
    appId: '1:863696538947:ios:8354ecd1cd21c62fe733f6',
    messagingSenderId: '863696538947',
    projectId: 'couple-finance-pig',
    storageBucket: 'couple-finance-pig.firebasestorage.app',
    iosBundleId: 'com.example.appTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBp6IBfjoBQzvhAEXAH0qsZs8qBUwoy8Rc',
    appId: '1:863696538947:ios:8354ecd1cd21c62fe733f6',
    messagingSenderId: '863696538947',
    projectId: 'couple-finance-pig',
    storageBucket: 'couple-finance-pig.firebasestorage.app',
    iosBundleId: 'com.example.appTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYjcPq19raPyTkJt2JkT1EO2PKhCmy2Lo',
    appId: '1:863696538947:web:09187ecd05cd29bde733f6',
    messagingSenderId: '863696538947',
    projectId: 'couple-finance-pig',
    authDomain: 'couple-finance-pig.firebaseapp.com',
    storageBucket: 'couple-finance-pig.firebasestorage.app',
    measurementId: 'G-72JS3T4N6J',
  );
}
